---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-left-arm
spec:
  action: delay
  direction: to
  mode: one
  selector:
    labelSelectors:
      "component": "podtato-head-left-arm"
  target:
    mode: all
    selector:
      labelSelectors:
        "component": "podtato-head-entry"
  delay:
    latency: "200ms"
    correlation: "100"
    jitter: "0ms"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-right-arm
spec:
  action: delay
  direction: to
  mode: one
  selector:
    labelSelectors:
      "component": "podtato-head-right-arm"
  target:
    mode: all
    selector:
      labelSelectors:
        "component": "podtato-head-entry"
  delay:
    latency: "400ms"
    correlation: "100"
    jitter: "0ms"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-left-leg
spec:
  action: delay
  direction: to
  mode: one
  selector:
    labelSelectors:
      "component": "podtato-head-left-leg"
  target:
    mode: all
    selector:
      labelSelectors:
        "component": "podtato-head-entry"
  delay:
    latency: "600ms"
    correlation: "100"
    jitter: "0ms"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-right-leg
spec:
  action: delay
  direction: to
  mode: one
  selector:
    labelSelectors:
      "component": "podtato-head-right-leg"
  target:
    mode: all
    selector:
      labelSelectors:
       "component": "podtato-head-entry"
  delay:
    latency: "800ms"
    correlation: "100"
    jitter: "0ms"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-hat
spec:
  action: delay
  direction: to
  mode: one
  selector:
    labelSelectors:
      "component": "podtato-head-hat"
  target:
    mode: all
    selector:
      labelSelectors:
       "component": "podtato-head-entry"
  delay:
    latency: "1000ms"
    correlation: "100"
    jitter: "0ms"
